### ISSUE TITLE
ideas or plans about aura's job in relation with polymerjs

### ISSUE THREAD

**Issue by HenriPodolski** [aurajs/aura#341]
I'm very curious on how aurajs could work together with polymerjs in a future version. Polymer loads components based on tags and bind functionalities to them, which is imho one of the important core functionalities of aurajs too. 

I red in #243 that aura differs to polymer, when it comes to structure and architecture. What makes sense, when I think about how messaging and decoupling is handled via the sandbox. 

But what are you guessing about aura's other roles in this stack and how could this be implemented? Do you have any ideas on that?

**Comment by CrowdHailer** [comment]
I was wondering if mission to refactor aura into a system of web components was progressing anywhere or if anyone was discussing it or even had a reason why aura doesnt belong in the web component world. 
Web components were not ready for production last yeah so why has aura stalled when it could still be useful in projects that are pre webcomponents

**Comment by kodi** [comment]
I wonder what is the current landscape looking like.

I see that there is not much activity around aura, it looks really nice, but I can't figure the status of it.

Is it still relevant?
Should we use something new?
How does it play with polymer now?

My primary case is building large scale web app.
