### ISSUE TITLE
how to Concatenate the files of the decoupled modules

### ISSUE THREAD

**Issue by wangyuelucky** [aurajs/aura#347]
As recommoned, our modules pub/sub events of interest rather than directly communicating with each other, that cutting off the direct relationship between modules.  

Our Module file structure as following:
```
Module A
- define File A
- Publish message A
- File A Logic
```

```
Module B
- define File B
- Subscribe message A
- File B Logic
```

```
Module C
- define File C
- Publish message C
- File C Logic
```

```
Module D
- define File D
- Subscribe message C
- File D Logic
```

 And I want the Concatenation output:

```
Release folder
- a.js   // combine Module A and B
- c.js   // combine Module C and D 
```

how can we achieve that?

**Comment by josephspens** [comment]
RequireJS is baked into Aura, you can use features like [bundles](http://requirejs.org/docs/api.html#config-bundles), [packages](http://requirejs.org/docs/api.html#packages), and [dependencies](http://requirejs.org/docs/api.html#config-deps) to build optimized files.

**Comment by wangyuelucky** [comment]
@josephspens  thanks all the same.
