### ISSUE TITLE
[BUSINESS CRITICAL] aurajs.com - github pages site is inaccessible

### ISSUE THREAD

**Issue by Ralphunter** [aurajs/aura#349]
When visiting either aurajs.com or aurajs.github.io I hit the following error page:

> Site Disabled
> Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.

> Are you the site owner? You can quickly fix this issue by updating the DNS record for your Pages site:

> If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a CNAME record that points to your-username.github.io.
> If you're not using a subdomain (example.com), make sure you have two A records set to the following IPs: 192.30.252.153 and 192.30.252.154

> More detailed instructions for [setting up a custom domain with GitHub pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/) are also available if you need more guidance.

> You can find more information about these changes in our [GitHub Pages legacy IP deprecation](https://github.com/blog/1917-github-pages-legacy-ip-deprecation) blog post. If you have any questions, please [contact support](https://github.com/contact).

This is business critical as I was unable to find out what aurajs is and thus cannot use it or spread its use.

**Comment by sbellity** [comment]
Hey @addyosmani I think you have the control of that domain, can you please check why this is happening ?

Thanks

**Comment by marlongichie** [comment]
Hello @sbellity , @addyosmani 

Any updates on this issue?

**Comment by addyosmani** [comment]
Hey folks. Sorry for the downtime! I was only just notified about this again on Twitter and will find out what happened to the domain.

**Comment by addyosmani** [comment]
DNS settings were apparently changed in GH documentation. I've updated and will let you know once the domain is back up.

**Comment by addyosmani** [comment]
The site is now back online.

**Comment by siddharthkp** [comment]
@addyosmani It's down again.
